### ISSUE TITLE
ObjectDisposedException when uploading package using .NET Core on Linux

### ISSUE THREAD

**Issue by kentcb** [Microsoft/service-fabric-client-dotnet#54] opened 2019-01-11 05:33 UTC
## Describe the bug
When calling the `UploadApplicationPackageAsync` on Linux using .NET Core 2.1, I get:
```
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
   at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory`1 buffer)
   at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
   at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
   at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

However, this doesn't seem to reproduce 100% of the time.

## To Reproduce
This is the relevant snippet of code (from a Cake build script):
```C#
var fabricClient = await new ServiceFabricClientBuilder()
    .UseEndpoints(clusterManagementUri)
    .UseX509Security(
        _ =>
        {
            var remoteSecuritySettings = new RemoteX509SecuritySettings(new List<string> { GenerateThumbprintFor(certificateBundle.X509Thumbprint) });
            var x509SecuritySettings = new X509SecuritySettings(automationCertificate, remoteSecuritySettings);
            return System.Threading.Tasks.Task.FromResult<SecuritySettings>(x509SecuritySettings);
        })
    .BuildAsync();

Information("Waiting for cluster management endpoint to become available.");

while (true)
{
    try
    {
        var clusterHealth = await fabricClient.Cluster.GetClusterHealthAsync();

        if (clusterHealth.AggregatedHealthState == HealthState.Ok)
        {
            Information("Connected to cluster management endpoint.");
            break;
        }

        Debug($"Cluster health is not OK. It is '{clusterHealth.AggregatedHealthState}' - waiting.");
    }
    catch (ServiceFabricRequestException)
    {
        Information("Unable to connect to Service Fabric management endpoint - waiting.");
    }

    await System.Threading.Tasks.Task.Delay(TimeSpan.FromSeconds(10));
}

Information("Uploading package to image store.");
// THIS IS WHERE THE EXCEPTION IS THROWN
await fabricClient
    .ImageStore
    .UploadApplicationPackageAsync(pkgDir, compressPackage: false, applicationPackagePathInImageStore: resourceNamePrefix);
```

## Expected behavior
No exception should be thrown.

## Additional context

I'm attempting to automate SF deployments, and in doing so have been running on both Linux (a Cake script running in a Docker container) and Windows (using LINQPad). I've only seen this particular issue on Linux, never on Windows. But like I said, it doesn't seem to _always_ trigger.

I'd be happy to provide any other information that would help diagnose.

**Comment by iyyappam** [comment] 2019-01-11 06:22
@kentcb, just like other thread, could you share the client side traces? If you are running the local cluster on Linux, the traces will be created on/mnt/SfDevCluster/Log. Please also provide the timestamp of the issue.

**Comment by kentcb** [comment] 2019-01-11 22:32
Hmm, this one will be more involved for me to collect, since I don't have SF running locally on the Linux image (it's just for CI). I'll have to look into getting that up and running first.

**Comment by amanbha** [comment] 2019-01-15 00:02
@kentcb Looking at the callstack, it seems to be an issue with System.Net.Security.SslState for Linux, could you please open issue in its repo at https://github.com/dotnet/corefx

**Comment by LucasFarley** [comment] 2019-01-20 17:57
I facing the same problem and due that the application is closing.

Unhandled Exception:
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
at System.Net.Security.SslState.ThrowIfExceptional()
at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory1 buffer) at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest) at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState) at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result) at System.Net.LazyAsyncResult.Complete(IntPtr userToken) at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e) at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Threading.ThreadPoolWorkQueue.Dispatch()System.ObjectDisposedException: Cannot access a disposed object. Object name: 'SslStream'. at System.Net.Security.SslState.ThrowIfExceptional() at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck) at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory1 buffer)
at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest)
at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState)
at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e)
at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.ThreadPoolWorkQueue.Dispatch()

Aborted (core dumped)

**Comment by amanbha** [comment] 2019-01-22 17:37
@LucasFarley Are you seeing it only on Linux as well?
Opened https://github.com/dotnet/corefx/issues/34746

**Comment by davidsh** [comment] 2019-01-22 20:49
This is a duplicate of https://github.com/dotnet/corefx/issues/34033.  The bug is fixed in current .NET Core 3.0 daily builds.

**Comment by amanbha** [comment] 2019-01-28 21:55
Closing as this is an issue in ,net core and is fixed in corefx repo.

**Closed as completed by amanbha** 2019-01-28 21:55 UTC
