### ISSUE TITLE
Wrong chunk calculation in UploadChunkAsync

### ISSUE THREAD

**Issue by DanYaari** [Microsoft/service-fabric-client-dotnet#56] opened 2019-01-17 10:00 UTC
Hi,

When trying to upload my application package files to the image store, I got the following exception:
`System.OverflowException: Arithmetic operation resulted in an overflow`

While looking at the code, I noticed a bug in `UploadChunkAsync`.
When calculating the chunk length, the calculation is as follows:
```
var length = chunkInfo.StartPosition - chunkInfo.EndPosition + 1;
var chunk = new byte[length];
```

This is a bug which results in negative length and therefore the new byte array results in an exception.
To reproduce, just upload any application package to the data store which has a file with size larger than `UploadLimitSizeInBytes`.

Thanks,
Dan Yaari

**Comment by amanbha** [comment] 2019-01-17 17:36
Thanks @DanYaari for reporting this. We will fix it in next release, if you would like to contribute please feel free to create a PR.
This is same as https://github.com/Microsoft/service-fabric-client-dotnet/issues/53

**Comment by amanbha** [comment] 2019-02-01 01:23
Closing as Dupe of #53

**Closed as completed by amanbha** 2019-02-01 01:23 UTC
Labels: bug
